### ISSUE TITLE
申请重新编译发布

### ISSUE THREAD

**Issue by qiu-noname** [project-mirai/chat-command#4]
0.3.0 jar 与 core 2.0-RC 二进制不兼容，源代码更新依赖后可以编译通过
```
2021-01-12 19:57:30 E/Chat Command: java.lang.NoSuchMethodError: 'net.mamoe.mirai.event.Listener net.mamoe.mirai.event.EventChannel.subscribeAlways$default(net.mamoe.mirai.event.EventChannel, kotlin.reflect.KClass, kotlin.coroutines.CoroutineContext, net.mamoe.mirai.event.Listener$ConcurrencyKind, net.mamoe.mirai.event.Listener$EventPriority, kotlin.jvm.functions.Function3, int, java.lang.Object)'
java.lang.NoSuchMethodError: 'net.mamoe.mirai.event.Listener net.mamoe.mirai.event.EventChannel.subscribeAlways$default(net.mamoe.mirai.event.EventChannel, kotlin.reflect.KClass, kotlin.coroutines.CoroutineContext, net.mamoe.mirai.event.Listener$ConcurrencyKind, net.mamoe.mirai.event.Listener$EventPriority, kotlin.jvm.functions.Function3, int, java.lang.Object)'
        at net.mamoe.mirai.console.plugins.chat.command.PluginMain.onEnable(PluginMain.kt:40)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:204)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
```

**Comment by Him188** [comment]
0.4.0
